version: "3"
services:

  backend:
    build:
      context: ./volume
    image: ai_flask
    ports:
      - "5000:5000"
    volumes:
      - ./volume/:/app
    labels:
      - maintainer="Fabian Wilhelm"



